name: hugo

on:
  push:
    branches: [ source ]

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true # Checkout theme submodules
      -
        name: Run Hugo
        uses: crazy-max/ghaction-hugo@v1
        with:
          #version: latest
          version: v0.74.3
          extended: true
          args: --cleanDestinationDir --verbose
      -
        name: Create `last-deployed.html` file
        if: success()
        run: echo "Last deployed on $(date -u)." > public/last-deployed.html
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: public
          fqdn: joeraut.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# Disabled due to Wayback Machine's rate-limiting
#      -
#        name: Archive pages to the Wayback Machine
#        if: success()
#        run: |
#          echo "Archiving all pages.."
#          grep -e loc public/sitemap.xml | sed 's|<loc>\(.*\)<\/loc>$|\1|g' | tr -d ' ' | xargs -I % sh -c "curl -s -D - 'https://web.archive.org/save/%' -o /dev/null; sleep 12" | grep 'location: http'
#          echo "Done."
