name: hugo

on:
  push:
    branches: [ source ]

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true # Checkout theme submodules
      -
        name: Run Hugo
        uses: crazy-max/ghaction-hugo@v1
        with:
          #version: latest
          version: v0.73.0 # latest version as of this commit
          extended: true
          args: --cleanDestinationDir --verbose
      -
        name: Create `last-deployed.html` file
        if: success()
        run: echo "Last deployed on $(date -u)." > public/last-deployed.html
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: public
          fqdn: joeraut.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Archive pages to the Wayback Machine
        if: success()
        run: |
          mkdir archive
          grep -e loc public/sitemap.xml | sed 's|<loc>\(.*\)<\/loc>$|\1|g' | tr -d ' ' > archive/urls.txt
          echo "Archiving $(cat archive/urls.txt | wc -l | tr -d ' ') pages.."
          cat archive/urls.txt | xargs -P 8 -I % curl -s -D - 'https://web.archive.org/save/%' -o /dev/null | grep 'location: http' | tee archive/archived-locations.txt
          cat archive/archived-locations.txt | cut -d ' ' -f 2- > public/last-archived.html
          echo "Done."
